version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile.web
    container_name: nginx-web
    ports:
      - "80:80"
    volumes:
      - ./app:/usr/share/nginx/html:ro
